// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/agentic/conversation": {
    params: {};
  };
  "/account/authorize": {
    params: {};
  };
  "/:locale?/account": {
    params: {
      "locale"?: string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/sitemap/:type/:page.xml": {
    params: {
      "locale"?: string;
      "type": string;
      "page": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/sitemap.xml": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/generative": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/plp/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/token": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/agentic/conversation" | "/account/authorize" | "/:locale?/account" | "/account/logout" | "/account/login" | "/robots.txt" | "/:locale?" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/products/:handle" | "/:locale?/sitemap.xml" | "/:locale?/generative" | "/:locale?/search" | "/:locale?/plp/*" | "/:locale?/cart" | "/:locale?/*" | "/token";
  };
  "routes/api.agentic.conversation.ts": {
    id: "routes/api.agentic.conversation";
    page: "/api/agentic/conversation";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/$(locale).account.tsx": {
    id: "routes/$(locale).account";
    page: "/:locale?/account";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/($locale).tsx": {
    id: "routes/($locale)";
    page: "/:locale?" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/products/:handle" | "/:locale?/sitemap.xml" | "/:locale?/generative" | "/:locale?/search" | "/:locale?/plp/*" | "/:locale?/cart" | "/:locale?/*";
  };
  "routes/($locale).sitemap.$type.$page[.xml].tsx": {
    id: "routes/($locale).sitemap.$type.$page[.xml]";
    page: "/:locale?/sitemap/:type/:page.xml";
  };
  "routes/($locale).products.$handle.tsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).[sitemap.xml].tsx": {
    id: "routes/($locale).[sitemap.xml]";
    page: "/:locale?/sitemap.xml";
  };
  "routes/($locale).generative.tsx": {
    id: "routes/($locale).generative";
    page: "/:locale?/generative";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).search.tsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale).plp.$.tsx": {
    id: "routes/($locale).plp.$";
    page: "/:locale?/plp/*";
  };
  "routes/($locale).cart.tsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart";
  };
  "routes/($locale).$.tsx": {
    id: "routes/($locale).$";
    page: "/:locale?/*";
  };
  "routes/token.tsx": {
    id: "routes/token";
    page: "/token";
  };
};